apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: retail-app
  labels:
    app: cart
    project: karatu-2025-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: public.ecr.aws/aws-containers/retail-store-sample-cart:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "256Mi"
              cpu: "256m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: retail-app
spec:
  selector:
    app: cart
  ports:
    - port: 80
      targetPort: 8080