apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: retail-app
  labels:
    project: karatu-2025-capstone
data:
  AWS_REGION: "us-east-1"
  MYSQL_PORT: "3306"
  POSTGRES_PORT: "5432"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"